nodeLinker: node-modules

packageExtensions:
  eslint-config-standard-with-typescript@*:
    dependencies:
      eslint-plugin-promise: "^6.0.0"
      eslint-plugin-import: "^2.25.2"
      eslint-plugin-n: "^15.0.0"
      "@typescript-eslint/eslint-plugin": "^5.0.0"
